idlist automation

diff --git a/bin/configure b/bin/configure
--- a/bin/configure
+++ b/bin/configure
@@ -1,20 +1,16 @@
 #!/bin/bash
 
-# bin/configure ott3.1 ott3.0 idlist
-#   - get properties.json file for ott3.0
+# bin/configure ott3.1 ott3.0
+#   - get properties.json file for ott3.0 (ott-HEAD)
 #   - create .mk include file defining xxx-PREVIOUS
-#   - advance (previous) ott from ott2.9 to ott3.0 = ott-NEW
-#   - advance idlist from ott2.9 to ott3.0 = idlist-NEW
-
-# idlist should have a sources: {...} property
+#   - advance (previous) ott from ott2.10 to ott3.0 = ott-NEW
 
 set -e
 
-[ $# = 3 ] || (echo wna; exit 1)
+[ $# = 2 ] || (echo wna; exit 1)
 
 new=$1
 old=$2
-idlist=$3
 
 if [ x$FILES_URL_PREFIX = x ]; then
     FILES_URL_PREFIX=http://files.opentreeoflife.org
@@ -22,29 +18,36 @@ fi
 
 # Get the old properties file.
 dir=r/$old
-if [ ! -e $dir/properties.json ]; then
-
+if [ -e $dir/properties.json ]; then
+    series=`bin/get $old series`
+else
     # Commands copied from fetch-archive.
     # (might be better to have a properties-only option for fetch-archive)
 
     series=`echo $old | egrep -o "[^0-9.]+"`
     i=$((${#series} - 1))
     [ ${series:i} = '-' ] && series=${series:0:$i}
-
-    PROP_URL=$FILES_URL_PREFIX/$series/$old/properties.json
-    mkdir -p $dir
-    if wget -q --output-document=$dir/properties.json.new $PROP_URL ; then
-        mv $dir/properties.json.new $dir/properties.json
-    else
-        echo "Failed to retrieve $PROP_URL"
-        exit 1
-    fi
 fi
 
+temp=/tmp/$old-properties.json.new
+PROP_URL=$FILES_URL_PREFIX/$series/$old/properties.json
+echo "Getting $PROP_URL"
+if wget -q --output-document=$temp $PROP_URL ; then
+    mkdir -p $dir
+    [ -e $dir/properties.json ] && echo "Overwriting $dir/properties.json"
+    mv $temp $dir/properties.json
+else
+    echo "Failed to retrieve $PROP_URL"
+    exit 1
+fi
+
+# Make ott-HEAD be an alias for previous OTT (e.g. ott-3.0)
+bin/set-head $series $old firm
+
+# Create config.mk based on "source" in old properties file
 python util/update_config.py <$dir/properties.json >config.mk
 
-series=`bin/get $old series`
-echo initiating $new
+echo Initiating $new = r/ott-NEW
 bin/new-version $series .tgz cc0
 bin/put $series-NEW name $new
 
@@ -54,15 +57,8 @@ bin/put $series-NEW name $new
 sep=`bin/get $old separator`
 drop=$((${#series} + ${#sep}))
 version=${new:drop}
-echo version is $version
 
 bin/put $series-NEW version $version
-
-# Needs to be made or fetched (somehow).
-# The following will at least force failure if the wrong version is used.
-
-rm -f r/idlist-HEAD
-ln -s idlist-`bin/get $old name` r/idlist-HEAD
 
 bin/put $series-NEW suffix .tgz
 bin/put $series-NEW legal cc0
