ticking over once again. dealt with bad pattern rules

diff --git a/bin/fetch-archive b/bin/fetch-archive
--- a/bin/fetch-archive
+++ b/bin/fetch-archive
@@ -2,6 +2,8 @@
 
 set -e
 
+[ $# = 1 ] || (echo "fetch-archive: arg count"; exit 1)
+
 # Retrieve one archive file from the files server
 
 if [ x$FILES_URL_PREFIX = x ]; then
@@ -10,50 +12,64 @@ fi
 
 # command line arg = archive/ncbi-20170425
 
-name=$1
-series=$2
+spec=$1
 
 dryrun=
 if [ x$DRYRUN != x ]; then dryrun=echo; fi
 
+# Set name and series
+if [ -e r/$spec/properties.json ]; then
+    name=`bin/get $spec name`
+    series=`bin/get $spec series`
+else
+    series=`echo $spec | egrep -o "[^0-9.]+"`
+    if [ x$series = x$spec ]; then
+        echo "fetch-archive: version specifier has no digits: $spec"
+        exit 1
+    else
+        i=$((${#series} - 1))
+        if [ ${series:i} = '-' ]; then
+            series=${series:0:$i}
+        fi
+    fi
+    name=$spec
+    echo "Series for $spec is $series"
+fi
+
 dir=r/$name
 
+# Not sure about this.  Should retrieve unconditionally (e.g. to get
+# new properties file)?
 if [ -e $dir/archive/.made ]; then
     echo "$dir archive is already present"
     exit 0
 fi
 
+# Get properties file and suffix
 $dryrun mkdir -p $dir
-
 PROP_URL=$FILES_URL_PREFIX/$series/$name/properties.json
-
 if [ x$dryrun = x ]; then
     if wget -q --output-document=$dir/properties.json.new $PROP_URL; then
         mv $dir/properties.json.new $dir/properties.json
+        suffix=`bin/get $name suffix`
     else
         echo "Failed to retrieve $PROP_URL"
         exit 1
     fi
-    suffix=`bin/get $name suffix`
 else
     echo wget -q --output-document=$dir/properties.json $PROP_URL
     suffix=.suffix
 fi
 
+# Get the archive file from server
 URL=$FILES_URL_PREFIX/$series/$name/$name$suffix
-
 $dryrun mkdir -p $dir/archive
 
 echo Fetching $URL
-
 if $dryrun wget -q --output-document=$dir/archive/downloaded.tmp $URL; then
-
-    # Finish up
-
     $dryrun mv -f $dir/archive/downloaded.tmp $dir/archive/archive$suffix
     $dryrun touch $dir/archive/.made
-
 else
-    echo "wget of $URL failed"
+    echo "Failed to retrieve $URL"
     exit 1
 fi
diff --git a/bin/unpack-archive b/bin/unpack-archive
--- a/bin/unpack-archive
+++ b/bin/unpack-archive
@@ -1,63 +1,65 @@
 #!/bin/bash
 
-# Extract source files from archive
+# Extract source files from archive.
+# No-op
 
 set -e
 
-# command line arg = e.g. archive/ncbi-20170425 source/ncbi-20170425
+[ $# = 1 ] || (echo "unpack-archive: arg count"; exit 1)
 
-if [ x$1 = x-h ]; then
-    headp=true
-    shift
-else
-    headp=false
-fi
+# command line arg = e.g. [-h] archive/ncbi-20170425 source/ncbi-20170425
 
 # N.b. spec might be foo-HEAD or foo-NEW
 spec=$1
-series=$2
 
 dryrun=
 if [ x$DRYRUN != x ]; then dryrun=echo; fi
 
-if $headp; then
-    if [ -e r/$series-HEAD ]; then
-        echo "$series-HEAD link exists; suppressing fetch of $spec"
-        echo "Do 'rm r/$series-HEAD' to force"
+dir=r/$spec
+
+if [ -e $dir/source/.made ]; then
+    if [ ! -e $dir/archive/.made ]; then
+        # If we already have the desired source, and there's no
+        # archive, assume it is new, and just use it.
+        echo "unpack-archive: source $spec is already present"
+        exit 0
+    elif [ ! $dir/archive/.made -nt $dir/source/.made ]; then
+        # If the archive is not newer than the source, then the
+        # source we already have is good enough, and there's no
+        # need to unpack.
+        echo "unpack-archive: source $spec is present and not older than archive"
         exit 0
     fi
 fi
 
-dir=r/$spec
-
 if ! [ -e $dir/archive/.made ]; then
-    bin/fetch-archive $spec $series
+    bin/fetch-archive $spec
 fi
 
 if ! [ -d $dir/. ]; then
-    echo "Missing directory $dir"
+    echo "unpack-archive: missing directory $dir"
     exit 1
 fi
 
 if ! [ -e $dir/properties.json ]; then
-    echo "Missing file $dir/properties.json"
+    echo "unpack-archive: missing file $dir/properties.json"
     exit 1
 fi
 
+name=`bin/get $spec name`
+series=`bin/get $spec series`
+suffix=`bin/get $spec suffix`
 
-dir=r/$spec
-
+dir=r/$name
 
 # For URL: strip off the version number, leaving only the resource name
-
-suffix=`bin/get $spec suffix`
 
 ar=$dir/archive/archive$suffix
 
 # TBD: re-unpack if archive is newer than source (-nt)
 
 if [ ! -e $ar ]; then
-    echo "Missing archive file $ar"
+    echo "unpack-archive: missing archive file $ar"
     exit 1
 fi
 
@@ -91,9 +93,4 @@ else
     fi
 
     echo "Unpacked $ar to $dest"
-fi
-
-if $headp; then
-    rm -f r/$series-HEAD
-    ln -s $spec r/$series-HEAD
 fi
